; PlatformIO Project Configuration File
; Proyecto ESP32 / ESP8266 - Envío de datos por WiFi

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Configuración del monitor serial
monitor_speed = 115200

; Forzar el puerto serie del ESP32 (ajusta si cambia el puerto)
upload_port = /dev/cu.usbserial-142220

; Librerías incluidas (WiFi y HTTP vienen con Arduino-ESP32)
lib_deps =
  knolleary/PubSubClient
  adafruit/DHT sensor library@^1.4.3

; ================== ENTORNO PARA ESP8266 (NodeMCU Amica) ==================
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

; Velocidad del monitor serie
monitor_speed = 115200

; Ajusta este puerto al que use tu NodeMCU
; Ejemplos típicos en macOS: /dev/cu.SLAB_USBtoUART, /dev/cu.wchusbserialXXXX
;upload_port = /dev/cu.SLAB_USBtoUART

; Librerías (WiFi y HTTP ya vienen con Arduino-ESP8266)
lib_deps =
  knolleary/PubSubClient
